### ISSUE TITLE
[TicketTool] The button creates two tickets.

### ISSUE THREAD

**Issue by batman202012** [AAA3A-AAA3A/AAA3A-cogs#10]
### What cog is this bug report for?

Ticket Tool

### Describe the bug

I'm on the latest version of the cog and clicking on the button creates double tickets.

**Comment by AAA3A-AAA3A** [comment]
Hello,
Thanks for reporting this issue.
Is there some error on the console?
Have a nice day,
AAA3A

**Comment by batman202012** [comment]
For creation no, also on deletion the transcript is not working
I have noticed every time I reload the cog it opens one extra ticket...

- `
Aug 20 02:17:59 tpun bash[2886]: discord.errors.HTTPException: 400 Bad Request (error code: 40060): Interaction has already been acknowledged.
Aug 20 02:17:59 tpun bash[2886]: Ignoring exception in on_button_click
Aug 20 02:17:59 tpun bash[2886]: Traceback (most recent call last):
Aug 20 02:17:59 tpun bash[2886]:   File "/home/discord/redenv/lib/python3.9/site-packages/discord/client.py", line 343, in _run_event
Aug 20 02:17:59 tpun bash[2886]:     await coro(*args, **kwargs)
Aug 20 02:17:59 tpun bash[2886]:   File "/home/discord/.local/share/Red-DiscordBot/data/tpun/cogs/CogManager/cogs/tickettool/tickettool.py", line 558, in on_button_click
Aug 20 02:17:59 tpun bash[2886]:     if not all(check(ctx) for check in ctx.command.checks):
Aug 20 02:17:59 tpun bash[2886]:   File "/home/discord/.local/share/Red-DiscordBot/data/tpun/cogs/Downloader/lib/dislash/interactions/interaction.py", line 320, in create_response
Aug 20 02:17:59 tpun bash[2886]:     await self.bot.http.request(
Aug 20 02:17:59 tpun bash[2886]:   File "/home/discord/redenv/lib/python3.9/site-packages/discord/http.py", line 254, in request
Aug 20 02:17:59 tpun bash[2886]:     raise HTTPException(r, data)
`

- `
Aug 20 02:17:59 tpun bash[2886]: discord.errors.HTTPException: 400 Bad Request (error code: 40060): Interaction has already been acknowledged.
Aug 20 02:18:10 tpun bash[2886]: [2022-08-20 02:18:10] [WARNING] py.warnings: /home/discord/.local/share/Red-DiscordBot/data/tpun/cogs/CogManager/cogs/tickettool/tickettool.py:567: RuntimeWarning: coroutine 'TicketTool.decorator.<locals>.pred' was never awaited
Aug 20 02:18:10 tpun bash[2886]:   if not permissions.read_messages and not permissions.read_message_history:
Aug 20 02:18:11 tpun bash[2886]: Ignoring exception in on_button_click
Aug 20 02:18:11 tpun bash[2886]: Traceback (most recent call last):
Aug 20 02:18:11 tpun bash[2886]:   File "/home/discord/redenv/lib/python3.9/site-packages/discord/client.py", line 343, in _run_event
Aug 20 02:18:11 tpun bash[2886]:     await coro(*args, **kwargs)
Aug 20 02:18:11 tpun bash[2886]:   File "/home/discord/.local/share/Red-DiscordBot/data/tpun/cogs/CogManager/cogs/tickettool/tickettool.py", line 570, in on_button_click
Aug 20 02:18:11 tpun bash[2886]:     if not all(check(ctx) for check in ctx.command.checks):
Aug 20 02:18:11 tpun bash[2886]:   File "/home/discord/.local/share/Red-DiscordBot/data/tpun/cogs/Downloader/lib/dislash/interactions/interaction.py", line 320, in create_response
Aug 20 02:18:11 tpun bash[2886]:     await self.bot.http.request(
Aug 20 02:18:11 tpun bash[2886]:   File "/home/discord/redenv/lib/python3.9/site-packages/discord/http.py", line 254, in request
Aug 20 02:18:11 tpun bash[2886]:     raise HTTPException(r, data)
`

- `
Aug 20 02:18:11 tpun bash[2886]: discord.errors.HTTPException: 400 Bad Request (error code: 40060): Interaction has already been acknowledged.
Aug 20 02:18:11 tpun bash[2886]: Ignoring exception in on_button_click
Aug 20 02:18:11 tpun bash[2886]: Traceback (most recent call last):
Aug 20 02:18:11 tpun bash[2886]:   File "/home/discord/redenv/lib/python3.9/site-packages/discord/client.py", line 343, in _run_event
Aug 20 02:18:11 tpun bash[2886]:     await coro(*args, **kwargs)
Aug 20 02:18:11 tpun bash[2886]:   File "/home/discord/.local/share/Red-DiscordBot/data/tpun/cogs/CogManager/cogs/tickettool/tickettool.py", line 570, in on_button_click
Aug 20 02:18:11 tpun bash[2886]:     if not all(check(ctx) for check in ctx.command.checks):
Aug 20 02:18:11 tpun bash[2886]:   File "/home/discord/.local/share/Red-DiscordBot/data/tpun/cogs/Downloader/lib/dislash/interactions/interaction.py", line 320, in create_response
Aug 20 02:18:11 tpun bash[2886]:     await self.bot.http.request(
Aug 20 02:18:11 tpun bash[2886]:   File "/home/discord/redenv/lib/python3.9/site-packages/discord/http.py", line 254, in request
Aug 20 02:18:11 tpun bash[2886]:     raise HTTPException(r, data)
`

- `
Aug 20 02:18:11 tpun bash[2886]: discord.errors.HTTPException: 400 Bad Request (error code: 40060): Interaction has already been acknowledged.
Aug 20 02:18:27 tpun bash[2886]: Traceback (most recent call last):
Aug 20 02:18:27 tpun bash[2886]:   File "/home/discord/.local/share/Red-DiscordBot/data/tpun/cogs/Downloader/lib/chat_exporter/construct/transcript.py", line 74, in export
Aug 20 02:18:27 tpun bash[2886]:   File "/home/discord/.local/share/Red-DiscordBot/data/tpun/cogs/Downloader/lib/chat_exporter/construct/transcript.py", line 39, in build_transcript
Aug 20 02:18:27 tpun bash[2886]:   File "/home/discord/.local/share/Red-DiscordBot/data/tpun/cogs/Downloader/lib/chat_exporter/construct/message.py", line 302, in gather
Aug 20 02:18:27 tpun bash[2886]:   File "/home/discord/.local/share/Red-DiscordBot/data/tpun/cogs/Downloader/lib/chat_exporter/construct/message.py", line 69, in construct_message
Aug 20 02:18:27 tpun bash[2886]:   File "/home/discord/.local/share/Red-DiscordBot/data/tpun/cogs/Downloader/lib/chat_exporter/construct/message.py", line 76, in build_message
Aug 20 02:18:27 tpun bash[2886]:   File "/home/discord/.local/share/Red-DiscordBot/data/tpun/cogs/Downloader/lib/chat_exporter/construct/message.py", line 164, in build_assets
Aug 20 02:18:27 tpun bash[2886]:   File "/home/discord/.local/share/Red-DiscordBot/data/tpun/cogs/Downloader/lib/chat_exporter/construct/assets/component.py", line 99, in flow
Aug 20 02:18:27 tpun bash[2886]: AttributeError: 'ActionRow' object has no attribute 'children'
`

**Comment by batman202012** [comment]
The first one I realised it wasn't working cause catergory close was not set (did not even create the text channel) Here is the traceback where it created 3 tickets
[create2.log](https://github.com/AAA3A-AAA3A/AAA3A-cogs/files/9387872/create2.log)

**Comment by AAA3A-AAA3A** [comment]
This error is caused by Dislash. Under dpy2, everything works fine. The interaction is triggered several times, which should not be done. This error existed on my first cog using the buttons under dpy1, and seemed to have been fixed in the init. I don't understand why it's coming back.
The explanation for the error: every time you reload the cog, Dislash creates a new instance of `InteractionClient`. The buttons are therefore executed the number of times this intsance is created.
A simple restart of the bot, without the next reload of TicketTool, should create only one instance, but I don't guarantee anything.

**Comment by batman202012** [comment]
That makes sense, I could restart my bot to fix it but since slashtags from phen-cogs is wonky as hell and won't load my 85 slash commands properly on restart and would cause me to restore them (and the I have to fix all the interactions permissions on the actual server), which I'm pretty sure would create a new instance of `InteractionClient` anyway. I think I'll just hold off until dpy2 comes out. I appreciate your time.

**Comment by AAA3A-AAA3A** [comment]
> which I'm pretty sure would create a new instance of InteractionClient anyway
SlashTags does not use Dislash, but raw requests to the Discord API.
But okay. Have a nice day.

**Comment by batman202012** [comment]
Oh awesome
