### ISSUE TITLE
[TicketTool] How do I delete the ticket channel and generate a transcript?

### ISSUE THREAD

**Issue by batman202012** [AAA3A-AAA3A/AAA3A-cogs#11]
### What cog is this feature request for?

Ticket Tool

### Describe the feature request in as much detail as possible

is there anyway I can just close a ticket and not have it saved in a different category? I'd really to prefer to have proper transcript than waste channels on tickets

Something like this:
![Screenshot 2022-08-09 110430](https://user-images.githubusercontent.com/18668066/183727066-20ef6478-0e34-4c77-bd03-80363da5d17e.png)
.

**Comment by AAA3A-AAA3A** [comment]
Hello,
Sorry for the late response.
All you need to do is enable transcripts in the cog settings and use the `[p]ticket delete` command.
Have à nice day,
AAA3A
