### ISSUE TITLE
[DiscordSearch] Allow people with administrator perms to use.

### ISSUE THREAD

**Issue by RawrUniversal** [AAA3A-AAA3A/AAA3A-cogs#13]
### What cog is this feature request for?

DiscordSearch

### Describe the feature request in as much detail as possible

It would be nice to allow people with administrator perms to use it.

**Comment by AAA3A-AAA3A** [comment]
Hello,
I will allow server administrators and permission administrators to use this cog.
Since every search makes a request to the Discord API, I will add a cooldown.
Thanks for this issue,
AAA3A
