### ISSUE TITLE
[ExportChannel] Error in `[p]exportchannel all` (`chat_exporter`).

### ISSUE THREAD

**Issue by Xg4dam** [AAA3A-AAA3A/AAA3A-cogs#14]
### What cog is this bug report for?

exportchannel 

### Describe the bug

When I try to do the exportchannel all command, I only get errors and can't get any variety of the command to work. 

### If there's an error, paste it here

```python
Exception in command 'exportchannel all'.
Traceback (most recent call last):
  File "{USERPROFILE}\redenv\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "{USERPROFILE}\Desktop\cogs\CogManager\cogs\exportchannel\exportchannel.py", line 75, in all
    file = discord.File(io.BytesIO(transcript.encode()),
AttributeError: 'NoneType' object has no attribute 'encode'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "{USERPROFILE}\redenv\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "{USERPROFILE}\redenv\lib\site-packages\redbot\core\commands\commands.py", line 832, in invoke
    await super().invoke(ctx)
  File "{USERPROFILE}\redenv\lib\site-packages\discord\ext\commands\core.py", line 1348, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "{USERPROFILE}\redenv\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "{USERPROFILE}\redenv\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'encode'
```

**Comment by AAA3A-AAA3A** [comment]
Hello,
Do you have an error message on the console, just before this one? This error occurs if the module used to export the messages has an error.
Have nice day,
AAA3A

**Comment by AAA3A-AAA3A** [comment]
Run this command in your venv. It's probably a module version problem.
````
python -m pip install --target <datapath>/cogs/Downloader/lib --upgrade --force-reinstall --no-cache-dir chat_exporter==1.7.3
````

**Comment by Xg4dam** [comment]
> 
![Untitled](https://user-images.githubusercontent.com/106568289/185723422-8e15a5cc-1229-491e-9bac-a4d53adfb90a.jpg)
This is all the output i had for it, running the command you gave didn't seem to solve it, i got the errors below when trying to run the command, though a lot of it installed.
![Untitled2](https://user-images.githubusercontent.com/106568289/185724956-f7b513d4-f77d-4585-9560-23f7e3eefbd9.jpg)

**Comment by AAA3A-AAA3A** [comment]
Installing the module unfortunately installed dpy2 while Red 3.4.18 still uses dpy 1.7.3. Run this command in your venv. 
And restart your bot.
Maybe restarting the bot will make the command work.
````
python -m pip install --upgrade --force-reinstall --no-cache-dir discord.py@git+https://github.com/Rapptz/discord.py@3d914e08e0c7df370987592affb3655d2a12f7d1#egg=discord.py
````

**Comment by Xg4dam** [comment]
I caught your edit too late and the bot is no longer starting 
![Untitled3](https://user-images.githubusercontent.com/106568289/185737686-31339aa2-ec50-476b-9672-23754d9c5026.jpg)

**Comment by AAA3A-AAA3A** [comment]
Sorry. Just reinstall Red with the correct requierement.
`python -m pip install -U --force-reinstall Red-DiscordBot`

**Comment by Xg4dam** [comment]
Okay I did, the cog still doesn't appear to be working.

**Comment by AAA3A-AAA3A** [comment]
What is the output of this command in your venv?
```
python -m pip freeze --path <datapath>/cogs/Downloader/lib
```

**Comment by AAA3A-AAA3A** [comment]
Run this command in your venv. The problem will be fixed.
````
python -m pip install --target <datapath>/cogs/Downloader/lib --upgrade --force-reinstall --no-cache-dir emoji==1.7
````
