### ISSUE TITLE
edittextchannel slowmodedelay 0` (with or without channel) just brings the embed back up and fails to remove slowmode

### ISSUE THREAD

**Issue by cag1585** [AAA3A-AAA3A/AAA3A-cogs#18]
### What cog is this bug report for?

edittextchannel

### Describe the bug

`edittextchannel slowmodedelay 0` (with or without channel) just brings the embed back up and fails to remove slowmode.

**Comment by AAA3A-AAA3A** [comment]
Hello,
Thanks for reporting it.
I will fix today.
Have a nice day,
AAA3A
