### ISSUE TITLE
`cmdset` cmd from CmdChannel is not accepting the Admin perms

### ISSUE THREAD

**Issue by Cool-aid-man** [AAA3A-AAA3A/AAA3A-cogs#19]
### What cog is this bug report for?

CmdChannel

### Describe the bug

The cmd `cmdset` from `CmdChannel` cog is not accepting the **Admin** perms, and it's showing,

> Only the owner of this server can access these commands!

Even tho, it should accept the admin perms as well as guild owner, according to the permission check on the cog.

### If there's an error, paste it here

```python
No Error. Just not accepting the administrative perms.
```

**Comment by AAA3A-AAA3A** [comment]
Hello,
Thanks for this issue.
I will edit soon.
Have a nice day,
AAA3A
