### ISSUE TITLE
[cmdchannel] The command `cmdchannel` became `CmdchanneL` after the recent update.

### ISSUE THREAD

**Issue by Cool-aid-man** [AAA3A-AAA3A/AAA3A-cogs#23]
### What cog is this bug report for?

CmdChannel

### Describe the bug

Hey aaa3a
I updated the cog today morning and now I'm seeing the **name** of the `command` got changed all of a sudden, to a weird name which is `CmdchanneL`

**Comment by Cool-aid-man** [comment]
![image](https://user-images.githubusercontent.com/84676543/204779583-d1a557a2-af16-488a-8cc5-f7c4a7646433.png)

**Comment by AAA3A-AAA3A** [comment]
Hello,
As you see in the description of the commands, you can now use `[p]cmdchannel`, `[p]cmduser` and `[p]cmduserchannel` as was originally possible before the implementation of the slash commands for dpy2. The bot should have informed you about this when updating the cog.
This group of commands was no longer supposed to be used for anything other than slash, but I'll rename it to `[p]cmdmock` (alias).
Have a nice day,
AAA3A
