### ISSUE TITLE
[DiscordEdit] Enable support for multiple permissions

### ISSUE THREAD

**Issue by Cool-aid-man** [AAA3A-AAA3A/AAA3A-cogs#28]
### What cog is this feature request for?

DiscordEdit 

### Describe the feature request in as much detail as possible

Heya 👋
       For the `edittextchannel perms` & `editvoicechannel perms` commands under `DiscordEdit` cog, currently these don't support passing __multiple perms__ (send msg, read msg etc) along with the cmd.

I think it'd be great to have that functionality to pass multiple perms for a specific user or users & roles(s) (as what it supports).
 
> On a side note: As a user you normally would want to give multiple perms to specific people rather than specific perm to multiple people (as this can be done just by giving a role to them then just add the role).

So if you could add the features to both the cmds would be super helpful.
Thanks

**Comment by AAA3A-AAA3A** [comment]
Hello,

Thanks for opening this issue.
I will add this feature to DiscordEdit.

Have a nice day,
AAA3A

**Comment by Cool-aid-man** [comment]
Thank aaa3a 

Have a good one

**Comment by Cool-aid-man** [comment]
Hey aaa3a
             I just found out that this new change of the `arguments` position can be very tricky when using in tags.
             
So, could you please re-arrange the **argument** structure of these two commands. 
> `<p>edittextchannel perms [#channel] [permissions] [true/false] [roles/users]`
> `<p>editvoicechannel perms [#channel] [permissions] [true/false] [roles/users]`

Sorry I should have mentioned this earlier (about keeping the arrangement same as before but just enabling multiple permissions)
Thanks 🙏

**Comment by AAA3A-AAA3A** [comment]
What is the problem with this change? I think it makes more sense this way because permissions are associated with roles or members.

**Comment by Cool-aid-man** [comment]
So, **suppose** someone wants to give `read_messages`, `send_messages`, `mention_everyone`, `external_emojis` (these specific) perms to a group of people which they will mention later on, in one command.

And considering they are using tags, to give those mentioned `group of people`, those permissions, they'd simply do,
> `{c:edittextchannel perms {args(1)} read_messages send_messages mention_everyone true {args(2+)}}`
Whereas the `{args(1)}` will be a #channel, and `{args(2+)}` will be any number of users, roles etc. could be one or more. 

> Now changing the arrangement, makes it more complicated to work with.

This arrangement gives them more room to play with perms. and makes it simple and easy to work with.

**Comment by AAA3A-AAA3A** [comment]
Why not just use `{c:edittextchannel perms {args(1)} {args(2+)} true read_messages send_messages mention_everyone}`? Tags will not parse the arguments in any other way anyway.

**Comment by Cool-aid-man** [comment]
Yes! ofcourse any combination would always work, without a doubt.
But I was saying from a normal user's point of view, what would they expect the cmd should act like, to make their life a bit easier.

And it's fine if we keep it as it is.
Thanks again
