### ISSUE TITLE
[CommandsButtons] Add Modals for params and making it sticky.

### ISSUE THREAD

**Issue by mrPauwHaan** [AAA3A-AAA3A/AAA3A-cogs#32]
### What cog is this feature request for?

commandsbuttons

### Describe the feature request in as much detail as possible

I would love to create a commandsbuttons for the audio cog, especially since people have difficulty remembering different commands. It would be a great addition if people are able to fill in an argument for a command with a modal.

For example, with a button connected to the [p]play command a modal would pop up, users only have to put in an URL and than it would execute. It would be a great addition.

Also, making the message sticky to the button of the channel would be nice especially in command channels

**Comment by AAA3A-AAA3A** [comment]
Hello,

It shouldn't be difficult to add a Modal to select the parameters, if the command was entered without one in the first place. On the other hand, I'm not convinced about making them sticky. It's not that simple, even if I understand that messages shouldn't be lost because of command responses. Perhaps ephemeral replies to messages? I'm not sure.

Have a nice day,
AAA3A

**Comment by mrPauwHaan** [comment]
Hi, and thanks for your reply,
A modal for parameters would already be a really significant improvement to our use case. 

For the sticky messages, I get that it can be complicated to implement. I am trying to think of other solutions to get a similar outcome, but haven't been able to come up with any yet.

**Comment by mrPauwHaan** [comment]
Giving multiple option: toggle ephemeral replies or giving the output in a different channel may be a way this could work.

**Comment by AAA3A-AAA3A** [comment]
CommandsButtons, RolesButtons and UrlButtons should soon be combined in a single UserfulButtons cog soon. When this is done, I may add an option to make them sticky. They would re-send the same content as the message they were on and delete it.

**Comment by mrPauwHaan** [comment]
Thanks, that sounds great! I am looking forward to it.

**Comment by AAA3A-AAA3A** [comment]
Hello,

Sorry for the wait. If you don't specify any command arguments when creating a commands-buttons, the cog will now ask you for the parameters with a Modal!
I haven't merged my 3 cogs yet, so the "sticky" function isn't done yet, but...

Thanks for this feature request.

![image](https://github.com/AAA3A-AAA3A/AAA3A-cogs/assets/89632044/3426a9eb-f3cb-422b-a7e2-0d78a4c22ec3)
![image](https://github.com/AAA3A-AAA3A/AAA3A-cogs/assets/89632044/ef8dccbe-9a66-41b2-845b-bc4cb95cae57)
