### ISSUE TITLE
Alias support

### ISSUE THREAD

**Issue by Potawto** [AAA3A-AAA3A/AAA3A-cogs#35]
### What cog is this feature request for?

CommandsButons

### Describe the feature request in as much detail as possible

Add support aliases as valid commands

My use case is making a button that sends a command with a parameter, instead of having the button pop up a dialog for the clicker to input the parameter.

`!alias add skipone skip 1`
`!commandsbuttons add # skipone ⏭️ 2 Next`

**Comment by AAA3A-AAA3A** [comment]
It should already be the case. I'll check.

**Comment by AAA3A-AAA3A** [comment]
And, if you specify a parameter yourself in the command, the Modal will not be displayed. Just use `[p]commandsbuttons add ... "skip 1" ...`.

**Comment by Potawto** [comment]
> And, if you specify a parameter yourself in the command, the Modal will not be displayed. Just use `[p]commandsbuttons add ... "skip 1" ...`.

I tried this, but it doesn't seem to work. The modal still pops up.

``!commandsbuttons add # "skip 1" ⏭️ 2 Next``

Am I doing something wrong?
