### ISSUE TITLE
[TempRoles] Allow `[p]temprole add` to overwrite the original duration if higher than remaining.

### ISSUE THREAD

**Issue by emshov74** [AAA3A-AAA3A/AAA3A-cogs#36]
### What cog is this feature request for?

temproles

### Describe the feature request in as much detail as possible

The temproles assign command returns a "⚠️ This member already has role" when used and the user already owns this role.

Could this be changed to where the duration of a temprole gets overwritten by the higher value?
So for example:

- If user has 3d left and a command is issued for the same role with 7d duration, the new duration is 7d;
- If user has 20d left and a command is issued for the same role with 7d duration, the duration remains 20d

Thank you for your time

**Comment by AAA3A-AAA3A** [comment]
Hello,

I'm thinking of adding this feature, but maybe with a confirmation before overriding?

Thanks for your suggestion,
Have a nice day,
AAA3A

**Comment by emshov74** [comment]
Maybe make it default to prompt for confirmation but also make it if you enter something like a "noconfirm" flag in the command that it just overwrites? Would be a nice thing for custom commands and the like

**Comment by AAA3A-AAA3A** [comment]
Or make a `[p]temproles edit [confirmation=False] <member> <role> <new_duration>` command? `[p]temprole add` would call it if the temprole have to be override.

**Comment by emshov74** [comment]
I'm fine with whatever you can get to work, since I am a very bad programmer :))

**Comment by AAA3A-AAA3A** [comment]
I've added `[p]temproles edit` and a confirmation to edit in `[p]temproles assign`. Ty for your suggestion.

![image](https://github.com/AAA3A-AAA3A/AAA3A-cogs/assets/89632044/69e31a26-9182-4e52-b81b-09b73670b2b2)
![image](https://github.com/AAA3A-AAA3A/AAA3A-cogs/assets/89632044/911c2c92-e6e7-4b94-be92-788e3e293096)
