### ISSUE TITLE
Minecraft Server Data cannot be retrieved

### ISSUE THREAD

**Issue by DanasaurUK** [AAA3A-AAA3A/AAA3A-cogs#50]
### What cog is this bug report for?

minecraft

### Describe the bug

The addserver and getserver functions of the minecraft cog are not working, I had a look at the py docs and it could be that the py library was updated? Unfortunately, I am limited in my understanding of code

**Comment by AAA3A-AAA3A** [comment]
Hello,

What is the problem? Any error? Maybe on the console?

Thank you for opening this issue,
Have a nice day,
AAA3A

**Comment by DanasaurUK** [comment]
Hi there,

My mistake, I got the format mixed up and was using the command !mcserver java [server IP]
