### ISSUE TITLE
[Minecraft] Edit an existing message instead of sending a new one.

### ISSUE THREAD

**Issue by ethanocurtis** [AAA3A-AAA3A/AAA3A-cogs#51]
### What cog is this feature request for?

MINECRAFT

### Describe the feature request in as much detail as possible

I was wanting to suggest having the bot edit the embed for updates rather than sending a new message for every update. Hopfully it is possible thank you.

**Comment by AAA3A-AAA3A** [comment]
Since Discord sets rate limits for editing posts older than X days, I'd rather not implement that right now.
