### ISSUE TITLE
[TicketTool] Replace Image for Tickets with the server Icon.

### ISSUE THREAD

**Issue by skaepz** [AAA3A-AAA3A/AAA3A-cogs#52]
### What cog is this feature request for?

tickettool

### Describe the feature request in as much detail as possible

So, I've been doing it manually but that is actually low-key annoying after every update, so I was curious if it is possible to actually change the Ticket image from the (p)settickettool message to the server Icon permanently

**Comment by AAA3A-AAA3A** [comment]
You can simply specify a bot message in `[p]settickettool message`.
