### ISSUE TITLE
Cooldown set to fixed in all cases

### ISSUE THREAD

**Issue by zarigata** [AAA3A-AAA3A/AAA3A-cogs#6]
### What cog is this bug report for?

react to command

### Describe the bug
![image](https://user-images.githubusercontent.com/39637452/176489090-a33e82bf-ab02-440a-b477-262e06edf4ad.png)

![image](https://user-images.githubusercontent.com/39637452/176488837-8f4d0c1f-c180-458a-92c1-72165bd61087.png)
in a time you create a command it wont go past the 1 time being that the cooldown si set to 1 time only

**Comment by AAA3A-AAA3A** [comment]
Hello,
What's wrong with my cog? What is the relationship with the economy cog?

**Comment by zarigata** [comment]
> Hello, What's wrong with my cog? What is the relationship with the economy cog?

i set the command in the rtc that in reaction with 💸 the bot would do a command on cassino, but it is stuck as a timestamp, dont really know how, as you can see in the print screen :
![image](https://user-images.githubusercontent.com/39637452/176691280-a78dba9f-de3b-4937-bacf-131d579cf624.png)
the time stamp does not change, i am not aware of what may doing this, i just wanted to make a cassino and other commands that are easier than tipping in chat

![image](https://user-images.githubusercontent.com/39637452/176690854-9b3dbe6b-0413-4c1c-92a5-554998c3aee3.png)

**Comment by AAA3A-AAA3A** [comment]
In your example, you don't seem to use the same user ("Allin", "Blackjack"), hence the cooldowns. Anyway, my cog is not able to do cooldowns. It's like calling the command yourself from Discord, with all the checks.
