### ISSUE TITLE
[Sudo] Lock into mod, admin, guild owner...

### ISSUE THREAD

**Issue by PBOwner** [AAA3A-AAA3A/AAA3A-cogs#60]
### What cog is this feature request for?

Sudo

### Describe the feature request in as much detail as possible

I was thinking you can run, for example, `[p]su user` to lock into the `user` permissions (base member), same with mod, admin, guildowner. Then to revert back to bot owner, you can just do `[p]unsu`

**Comment by AAA3A-AAA3A** [comment]
To implement this functionality, it would be necessary to override the `bot.is_mod` and `bot.is_admin` methods, which I prefer to avoid, as this is not the main purpose of this cog.

**Comment by LeDeathAmongst** [comment]
This seem useful. Maybe make separate cog for this?
