### ISSUE TITLE
TicketTool - Setting to Disable Closure Reason

### ISSUE THREAD

**Issue by karutoil** [AAA3A-AAA3A/AAA3A-cogs#62]
### What cog is this feature request for?

TicketTool

### Describe the feature request in as much detail as possible

Create a setting it could be per profile or globally that can enable/disable entering a ticket reason.

Maybe the default one being Ticket Closed by **Username**

**Comment by AAA3A-AAA3A** [comment]
You can switch to Tickets, my TicketTool's rewrite, which has this possibility.
