### ISSUE TITLE
[RolesButtons&UrlButtons] Allow both cogs to be used simultaneously on the same message.

### ISSUE THREAD

**Issue by batman202012** [AAA3A-AAA3A/AAA3A-cogs#8]
### What cog is this bug report for?

Urlbuttons and Rolesbuttons

### Describe the bug

Url buttons and role buttons clear each others buttons when used on the same message.

### If there's an error, paste it here

```python
No traceback recieved in console
```

**Comment by AAA3A-AAA3A** [comment]
Hello,
Thank you for opening this issue.
I'm sorry, but I'm not going to add this functionality to my cogs, as it would break the logic of the code (under dpy2 at least).
A message can't have 2 Views with dpy2 and I would have to modify both to work on the same View, which is too difficult without modifying everything.
If you need both types of buttons, just send two messages that follow each other and add the buttons to each.
Have a nice day,
AAA3A
